# Generated by Django 2.2.4 on 2019-10-18 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0014_remove_story_count'),
        ('users', '0003_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scenario.Story'),
        ),
    ]
