# Generated by Django 2.2.4 on 2019-10-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_counter_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Story'),
        ),
    ]
