# Generated by Django 2.2.4 on 2019-10-18 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_counter_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='profile',
        ),
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
