# Generated by Django 2.2.4 on 2019-10-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191018_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='story',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='story_progress',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='user',
        ),
    ]
