# Generated by Django 2.2.4 on 2019-10-18 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0014_remove_story_count'),
        ('users', '0008_auto_20191018_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scenario.Story'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='story_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
