# Generated by Django 2.2.4 on 2019-10-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191018_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked_story',
            old_name='Like_story',
            new_name='like_story',
        ),
    ]
