# Generated by Django 2.2.4 on 2019-10-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191018_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='story_finish',
            field=models.BooleanField(default=False),
        ),
    ]
