# Generated by Django 2.2.4 on 2019-10-18 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_counter_story_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_story',
            name='like_story',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
