# Generated by Django 2.2.4 on 2019-10-19 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191018_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_story',
            name='like_story',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
