# Generated by Django 2.2.4 on 2019-10-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191019_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
    ]
