# Generated by Django 2.2.4 on 2019-10-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191019_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
