# Generated by Django 2.2.4 on 2019-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='choice_chose',
            field=models.IntegerField(default=0),
        ),
    ]
