# Generated by Django 2.2.4 on 2019-12-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20191210_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked_Story',
        ),
    ]
