# Generated by Django 2.2.4 on 2019-12-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20191214_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.StoryComment'),
        ),
    ]
