# Generated by Django 2.2.4 on 2019-12-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20191214_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_story', to='scenario.Story'),
        ),
    ]
