# Generated by Django 2.2.4 on 2019-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20191214_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='storycomment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='_storycomment_reply_+', to='users.StoryComment'),
        ),
    ]
