# Generated by Django 2.2.4 on 2019-12-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0033_story_tags'),
        ('users', '0035_auto_20191214_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.TextField()),
                ('award_description', models.TextField()),
                ('award_image', models.ImageField(default='default.jpg', upload_to='award_pics')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(max_length=1100)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported')),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ReportCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(max_length=1100)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported')),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(max_length=1200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ticket Created')),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SupportCategories')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='block_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_followers',
            field=models.ManyToManyField(blank=True, related_name='pending_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow_Request',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ReportCategories'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reporter', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reporter', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Story'),
        ),
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='awards', to='users.Awards'),
        ),
    ]
