# Generated by Django 2.2.4 on 2019-12-15 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20191215_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
