# Generated by Django 2.2.4 on 2019-12-16 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_auto_20191215_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
