# Generated by Django 2.2.4 on 2019-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20191216_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
