# Generated by Django 2.2.4 on 2019-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_profile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(default='gxI0drJelo', max_length=10),
        ),
    ]
