# Generated by Django 2.2.4 on 2019-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20191216_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='ruqkBJaMWv', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
