# Generated by Django 2.2.4 on 2019-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20191216_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='GQWnyycK9h', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
