# Generated by Django 2.2.4 on 2019-12-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20191216_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='referred_by',
            new_name='referrer_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='wwKjKEzMSn', max_length=10),
        ),
    ]
