# Generated by Django 2.2.4 on 2019-12-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20191218_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='hDPggvoZNp', max_length=10),
        ),
    ]
