# Generated by Django 2.2.4 on 2019-12-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20191218_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='BlP93IQ3xo', max_length=10),
        ),
    ]
