# Generated by Django 2.2.4 on 2019-12-19 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0034_auto_20191218_0248'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0051_auto_20191218_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='Nxot07wTwe', max_length=10),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.Story')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reason', to='users.NotificationCategories')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
