# Generated by Django 2.2.4 on 2019-12-19 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20191219_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='CyKW1SPOql', max_length=10),
        ),
    ]
