# Generated by Django 2.2.4 on 2019-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20191219_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='users.Notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='old_notifications',
            field=models.ManyToManyField(blank=True, related_name='old_notifications', to='users.Notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='Ms2OM1ymyz', max_length=10),
        ),
    ]
