# Generated by Django 2.2.4 on 2019-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20191219_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='WDMxtawP63', max_length=10),
        ),
    ]
