# Generated by Django 2.2.4 on 2019-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20191219_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcategories',
            name='notification_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='GBdfrMje7v', max_length=10),
        ),
    ]
