# Generated by Django 2.2.4 on 2019-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20191219_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='RkHoFr7AYA', max_length=10),
        ),
    ]
