# Generated by Django 2.2.4 on 2019-12-25 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0064_auto_20191225_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Thread_Message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='1nn5We1Gn8', max_length=10),
        ),
    ]
