# Generated by Django 2.2.4 on 2019-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20191225_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='kHLX7DSZsr', max_length=10),
        ),
    ]
