# Generated by Django 2.2.4 on 2019-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20191227_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='finish_ft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counter',
            name='story_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='OmlPHYYPt9', max_length=10),
        ),
    ]
