# Generated by Django 2.2.4 on 2019-12-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20191227_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='restarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='tFQFVZemgm', max_length=10),
        ),
    ]
