# Generated by Django 2.2.4 on 2019-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20191227_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='times_restarted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='U6kYfsujyq', max_length=10),
        ),
    ]
