# Generated by Django 2.2.4 on 2019-12-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20191227_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='mgMcDN62Zk', max_length=10),
        ),
    ]
