# Generated by Django 2.2.4 on 2022-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20191227_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default='1N7eiR5tRT', max_length=10),
        ),
    ]
