# Generated by Django 2.2.4 on 2019-08-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=100)),
                ('story_description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_description', models.TextField(max_length=600)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(max_length=400)),
                ('choice_life', models.BooleanField(default=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.Scene')),
            ],
        ),
    ]
