# Generated by Django 2.2.4 on 2019-08-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicescene', to='scenario.Scene'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenestory', to='scenario.Story'),
        ),
    ]
