# Generated by Django 2.2.4 on 2019-08-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_auto_20190805_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_death',
            field=models.TextField(default='This choice ended game'),
        ),
    ]
