# Generated by Django 2.2.4 on 2019-08-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_choice_choice_death'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_life',
            new_name='choice_continue',
        ),
    ]
