# Generated by Django 2.2.4 on 2019-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_auto_20190806_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_continue',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_end_success',
            field=models.TextField(default='Congratulations, you have made it to the end :) ', max_length=400),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_death',
            field=models.TextField(default='This choice ended game sorry', max_length=400),
        ),
    ]
