# Generated by Django 2.2.4 on 2019-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20190807_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_death',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_end_success',
        ),
        migrations.AddField(
            model_name='choice',
            name='end_f',
            field=models.TextField(default='This choice ended game sorry', max_length=400),
        ),
        migrations.AddField(
            model_name='choice',
            name='end_s',
            field=models.TextField(default='Congratulations, you have made it to the end :) ', max_length=400),
        ),
    ]
