# Generated by Django 2.2.4 on 2019-10-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0013_story_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='count',
        ),
    ]
