# Generated by Django 2.2.4 on 2019-10-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0014_remove_story_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_pic',
            field=models.ImageField(default='default.jpg', upload_to='story_pics'),
        ),
    ]
