# Generated by Django 2.2.4 on 2019-10-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0015_story_story_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_pic',
            field=models.ImageField(default='default.jpg', upload_to='scene_pics'),
        ),
    ]
