# Generated by Django 2.2.4 on 2019-12-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0017_auto_20191018_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_do',
            field=models.TextField(default='this text will show before scene text / What does this choice do ?', max_length=250),
        ),
        migrations.AddField(
            model_name='choice',
            name='fail_pic',
            field=models.ImageField(default='default.jpg', upload_to='scene_pics'),
        ),
        migrations.AddField(
            model_name='choice',
            name='success_pic',
            field=models.ImageField(default='default.jpg', upload_to='scene_pics'),
        ),
    ]
