# Generated by Django 2.2.4 on 2019-12-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0019_auto_20191210_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='fail_pic',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='success_pic',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_pic',
            field=models.ImageField(default='default.jpg', upload_to='choice_pic'),
        ),
    ]
