# Generated by Django 2.2.4 on 2019-12-11 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0020_auto_20191210_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='story_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
