# Generated by Django 2.2.4 on 2019-12-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0022_auto_20191211_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
    ]
