# Generated by Django 2.2.4 on 2019-12-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0027_auto_20191212_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='_story_likes_+', to='scenario.Story'),
        ),
    ]
