# Generated by Django 2.2.4 on 2019-12-14 21:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('scenario', '0032_auto_20191212_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
