# Generated by Django 2.2.4 on 2019-12-18 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario', '0033_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='reshares',
            field=models.ManyToManyField(blank=True, related_name='reshares_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
