# Generated by Django 2.2.4 on 2019-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0034_auto_20191218_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
