# Generated by Django 2.2.4 on 2019-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0035_story_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
